name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  # Fills the dep cache so parallel jobs can start faster.
  # No sense in running tests if we can't install correctly.
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3

  # test:
  #   name: "Tests"
  #   runs-on: ubuntu-latest
  #   needs: [setup]

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: wyvox/action-setup-pnpm@v3
  #     - run: pnpm test

  test_eslint-plugin-ember:
    name: "eslint-plugin-ember"
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: node ./scripts/eslint-plugin-ember-test.mjs

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - name: Lint
        run: pnpm lint

